version: '3.8'

services:
  app:
    image: ghcr.io/ralphschuler/jamesbotler:latest
    restart: always
    env_file:
      - .env
    volumes:
      - translationsDB:/app/translations.db
    links:
      - tor0
      - tor1
      - tor2
      - tor3
      - tor4
      - tor5
      - tor6
      - tor7
      - tor8
      - tor9
  watchtower:
    image: containrrr/watchtower
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    depends_on:
      - app
  tor0:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=DE
  tor1:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=US
  tor2:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=FI
  tor3:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=FR
  tor4:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=HK
  tor5:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=MX
  tor6:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=NL
  tor7:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=RU
  tor8:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=ES
  tor9:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=CH

volumes:
  translationsDB: