version: '3.8'

services:
  production:
    image: ghcr.io/ralphschuler/jamesbotler:1.0.8
    restart: always
    env_file:
      - .prod.env
    volumes:
      - translationsDB:/app/translations.db
    links:
      - tor0
      - tor1
      - tor2
      - tor3
      - tor4
      - tor5
      - tor6
      - tor7
      - tor8
      - tor9
  staging:
    build: .
    restart: always
    env_file:
      - .env
    links:
      - tor0
      - tor1
      - tor2
      - tor3
      - tor4
      - tor5
      - tor6
      - tor7
      - tor8
      - tor9
  tor0:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=DE
  tor1:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=US
  tor2:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=FI
  tor3:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=FR
  tor4:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=HK
  tor5:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=MX
  tor6:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=NL
  tor7:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=RU
  tor8:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=ES
  tor9:
    image: dperson/torproxy
    restart: always
    environment:
      - LOCATION=CH

volumes:
  translationsDB: