name: Analysis

on: 
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Run OSSAR
        uses: github/ossar-action@v1
        id: ossar
        
      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}