name: Anchore Analysis

on: 
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 1 * * 0'

jobs:
  anchore-analysis:
    strategy:
        fail-fast: false
        matrix:
          language: ['javascript']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    
    - name: Run Anchore scan
      uses: anchore/scan-action@main
      with:
        image: "localbuild/testimage:latest"
        acs-report-enable: true
    
    - name: Upload Anchore report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}