name: Auto Tag
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code 
      uses: actions/checkout@v2

    - name: Auto Tag
      uses: Klemensas/action-autotag@stable
      with:
        tag_prefix: "v"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"