name: Code Check
on:
  push:
  pull_request

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code 
      uses: actions/checkout@v2

    - name: Lint Javascript
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}