name: Quality Analysis

on: 
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 1 * * 0'

jobs:
  quality-analysis:
    strategy:
        fail-fast: false
        matrix:
          language: ['javascript']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      
      - name: Auto build
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Upload CodeQL Analysis Report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif