name: Tag
on:
  push:
    branches: [master]

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code 
      uses: actions/checkout@v2

    - name: Create Changelog
      id: changelog
      uses: heineiuo/create-changelogs@master

    - name: Tag
      uses: Klemensas/action-autotag@stable
      with:
        tag_prefix: "v"
        GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
        changelog_structure: ${{ steps.changelog.outputs.changelogs }}