name: Tah
on:
  push:
    branches:
      - master

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code 
      uses: actions/checkout@v2

    - name: Tag
      uses: Klemensas/action-autotag@stable
      with:
        tag_prefix: "v"
        GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"